### ISSUE TITLE
unable to support sls v3

### ISSUE THREAD

**Issue by yeukfei02** [dhollerbach/actions.serverless-with-python-requirements#13]
hi..

does this github actions lib able to use for python with serverless framework v3?
I try in my repo with sls v3 is not working for auto-deploy

thanks.

**Comment by dhollerbach** [comment]
@yeukfei02  Greetings - I just updated this action to use the latest Serverless framework. Serverless wants us to use environments variables rather than passing in command line options so you can do that instead using this action. I've created and `examples` directory which shows everything I used when testing and deploying this action and should give you a good start.

Check it out and let me know if you have any remaining issues.

-Dave
